// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/api/files/stat/stat.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	commands "expire-share/internal/domain/dto/files/commands"
	results "expire-share/internal/domain/dto/files/results"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFilesStatGetter is a mock of FilesStatGetter interface.
type MockFilesStatGetter struct {
	ctrl     *gomock.Controller
	recorder *MockFilesStatGetterMockRecorder
}

// MockFilesStatGetterMockRecorder is the mock recorder for MockFilesStatGetter.
type MockFilesStatGetterMockRecorder struct {
	mock *MockFilesStatGetter
}

// NewMockFilesStatGetter creates a new mock instance.
func NewMockFilesStatGetter(ctrl *gomock.Controller) *MockFilesStatGetter {
	mock := &MockFilesStatGetter{ctrl: ctrl}
	mock.recorder = &MockFilesStatGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFilesStatGetter) EXPECT() *MockFilesStatGetterMockRecorder {
	return m.recorder
}

// GetFilesStat mocks base method.
func (m *MockFilesStatGetter) GetFilesStat(ctx context.Context, command commands.GetFilesStat) (*results.GetFilesStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesStat", ctx, command)
	ret0, _ := ret[0].(*results.GetFilesStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilesStat indicates an expected call of GetFilesStat.
func (mr *MockFilesStatGetterMockRecorder) GetFilesStat(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesStat", reflect.TypeOf((*MockFilesStatGetter)(nil).GetFilesStat), ctx, command)
}
