// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/api/files/getAll/get_all.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	commands "expire-share/internal/domain/dto/files/commands"
	results "expire-share/internal/domain/dto/files/results"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAllFilesGetter is a mock of AllFilesGetter interface.
type MockAllFilesGetter struct {
	ctrl     *gomock.Controller
	recorder *MockAllFilesGetterMockRecorder
}

// MockAllFilesGetterMockRecorder is the mock recorder for MockAllFilesGetter.
type MockAllFilesGetterMockRecorder struct {
	mock *MockAllFilesGetter
}

// NewMockAllFilesGetter creates a new mock instance.
func NewMockAllFilesGetter(ctrl *gomock.Controller) *MockAllFilesGetter {
	mock := &MockAllFilesGetter{ctrl: ctrl}
	mock.recorder = &MockAllFilesGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllFilesGetter) EXPECT() *MockAllFilesGetterMockRecorder {
	return m.recorder
}

// GetAllFiles mocks base method.
func (m *MockAllFilesGetter) GetAllFiles(ctx context.Context, command commands.GetAllFiles) ([]results.GetFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllFiles", ctx, command)
	ret0, _ := ret[0].([]results.GetFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllFiles indicates an expected call of GetAllFiles.
func (mr *MockAllFilesGetterMockRecorder) GetAllFiles(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllFiles", reflect.TypeOf((*MockAllFilesGetter)(nil).GetAllFiles), ctx, command)
}
