// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/middlewares/parsing.go

// Package mocks is a generated GoMock package.
package mocks

import (
	config "expire-share/internal/config"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDefaultSetter is a mock of DefaultSetter interface.
type MockDefaultSetter struct {
	ctrl     *gomock.Controller
	recorder *MockDefaultSetterMockRecorder
}

// MockDefaultSetterMockRecorder is the mock recorder for MockDefaultSetter.
type MockDefaultSetterMockRecorder struct {
	mock *MockDefaultSetter
}

// NewMockDefaultSetter creates a new mock instance.
func NewMockDefaultSetter(ctrl *gomock.Controller) *MockDefaultSetter {
	mock := &MockDefaultSetter{ctrl: ctrl}
	mock.recorder = &MockDefaultSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDefaultSetter) EXPECT() *MockDefaultSetterMockRecorder {
	return m.recorder
}

// SetDefault mocks base method.
func (m *MockDefaultSetter) SetDefault(cfg config.Service) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDefault", cfg)
}

// SetDefault indicates an expected call of SetDefault.
func (mr *MockDefaultSetterMockRecorder) SetDefault(cfg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDefault", reflect.TypeOf((*MockDefaultSetter)(nil).SetDefault), cfg)
}
