// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/admin/users/getAll/get_all.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	commands "expire-share/internal/domain/dto/users/commands"
	results "expire-share/internal/domain/dto/users/results"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAllUsersGetter is a mock of AllUsersGetter interface.
type MockAllUsersGetter struct {
	ctrl     *gomock.Controller
	recorder *MockAllUsersGetterMockRecorder
}

// MockAllUsersGetterMockRecorder is the mock recorder for MockAllUsersGetter.
type MockAllUsersGetterMockRecorder struct {
	mock *MockAllUsersGetter
}

// NewMockAllUsersGetter creates a new mock instance.
func NewMockAllUsersGetter(ctrl *gomock.Controller) *MockAllUsersGetter {
	mock := &MockAllUsersGetter{ctrl: ctrl}
	mock.recorder = &MockAllUsersGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAllUsersGetter) EXPECT() *MockAllUsersGetterMockRecorder {
	return m.recorder
}

// GetAllUsers mocks base method.
func (m *MockAllUsersGetter) GetAllUsers(ctx context.Context, command commands.GetAllUsers) (*results.GetAllUsers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx, command)
	ret0, _ := ret[0].(*results.GetAllUsers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockAllUsersGetterMockRecorder) GetAllUsers(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockAllUsersGetter)(nil).GetAllUsers), ctx, command)
}
