// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/download/download.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	commands "expire-share/internal/domain/dto/files/commands"
	results "expire-share/internal/domain/dto/files/results"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileDownloader is a mock of FileDownloader interface.
type MockFileDownloader struct {
	ctrl     *gomock.Controller
	recorder *MockFileDownloaderMockRecorder
}

// MockFileDownloaderMockRecorder is the mock recorder for MockFileDownloader.
type MockFileDownloaderMockRecorder struct {
	mock *MockFileDownloader
}

// NewMockFileDownloader creates a new mock instance.
func NewMockFileDownloader(ctrl *gomock.Controller) *MockFileDownloader {
	mock := &MockFileDownloader{ctrl: ctrl}
	mock.recorder = &MockFileDownloaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileDownloader) EXPECT() *MockFileDownloaderMockRecorder {
	return m.recorder
}

// DownloadFile mocks base method.
func (m *MockFileDownloader) DownloadFile(ctx context.Context, command commands.DownloadFile) (*results.DownloadFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadFile", ctx, command)
	ret0, _ := ret[0].(*results.DownloadFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DownloadFile indicates an expected call of DownloadFile.
func (mr *MockFileDownloaderMockRecorder) DownloadFile(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadFile", reflect.TypeOf((*MockFileDownloader)(nil).DownloadFile), ctx, command)
}
