// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/api/files/delete/delete.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	commands "expire-share/internal/domain/dto/files/commands"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileDeleter is a mock of FileDeleter interface.
type MockFileDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockFileDeleterMockRecorder
}

// MockFileDeleterMockRecorder is the mock recorder for MockFileDeleter.
type MockFileDeleterMockRecorder struct {
	mock *MockFileDeleter
}

// NewMockFileDeleter creates a new mock instance.
func NewMockFileDeleter(ctrl *gomock.Controller) *MockFileDeleter {
	mock := &MockFileDeleter{ctrl: ctrl}
	mock.recorder = &MockFileDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileDeleter) EXPECT() *MockFileDeleterMockRecorder {
	return m.recorder
}

// DeleteFile mocks base method.
func (m *MockFileDeleter) DeleteFile(ctx context.Context, command commands.DeleteFile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFile", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFile indicates an expected call of DeleteFile.
func (mr *MockFileDeleterMockRecorder) DeleteFile(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFile", reflect.TypeOf((*MockFileDeleter)(nil).DeleteFile), ctx, command)
}
