// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/admin/users/roles/revoke/revoke.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	commands "expire-share/internal/domain/dto/users/commands"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRoleRevoker is a mock of RoleRevoker interface.
type MockRoleRevoker struct {
	ctrl     *gomock.Controller
	recorder *MockRoleRevokerMockRecorder
}

// MockRoleRevokerMockRecorder is the mock recorder for MockRoleRevoker.
type MockRoleRevokerMockRecorder struct {
	mock *MockRoleRevoker
}

// NewMockRoleRevoker creates a new mock instance.
func NewMockRoleRevoker(ctrl *gomock.Controller) *MockRoleRevoker {
	mock := &MockRoleRevoker{ctrl: ctrl}
	mock.recorder = &MockRoleRevokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleRevoker) EXPECT() *MockRoleRevokerMockRecorder {
	return m.recorder
}

// RevokeRole mocks base method.
func (m *MockRoleRevoker) RevokeRole(ctx context.Context, command commands.RevokeRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevokeRole", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// RevokeRole indicates an expected call of RevokeRole.
func (mr *MockRoleRevokerMockRecorder) RevokeRole(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevokeRole", reflect.TypeOf((*MockRoleRevoker)(nil).RevokeRole), ctx, command)
}
