// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/api/auth/logout/logout.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	commands "expire-share/internal/domain/dto/auth/commands"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserLogout is a mock of UserLogout interface.
type MockUserLogout struct {
	ctrl     *gomock.Controller
	recorder *MockUserLogoutMockRecorder
}

// MockUserLogoutMockRecorder is the mock recorder for MockUserLogout.
type MockUserLogoutMockRecorder struct {
	mock *MockUserLogout
}

// NewMockUserLogout creates a new mock instance.
func NewMockUserLogout(ctrl *gomock.Controller) *MockUserLogout {
	mock := &MockUserLogout{ctrl: ctrl}
	mock.recorder = &MockUserLogoutMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserLogout) EXPECT() *MockUserLogoutMockRecorder {
	return m.recorder
}

// Logout mocks base method.
func (m *MockUserLogout) Logout(ctx context.Context, command commands.Logout) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logout", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// Logout indicates an expected call of Logout.
func (mr *MockUserLogoutMockRecorder) Logout(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logout", reflect.TypeOf((*MockUserLogout)(nil).Logout), ctx, command)
}
