// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/admin/users/roles/assign/assign.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	commands "expire-share/internal/domain/dto/users/commands"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRoleAssigning is a mock of RoleAssigning interface.
type MockRoleAssigning struct {
	ctrl     *gomock.Controller
	recorder *MockRoleAssigningMockRecorder
}

// MockRoleAssigningMockRecorder is the mock recorder for MockRoleAssigning.
type MockRoleAssigningMockRecorder struct {
	mock *MockRoleAssigning
}

// NewMockRoleAssigning creates a new mock instance.
func NewMockRoleAssigning(ctrl *gomock.Controller) *MockRoleAssigning {
	mock := &MockRoleAssigning{ctrl: ctrl}
	mock.recorder = &MockRoleAssigningMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleAssigning) EXPECT() *MockRoleAssigningMockRecorder {
	return m.recorder
}

// AssignRole mocks base method.
func (m *MockRoleAssigning) AssignRole(ctx context.Context, command commands.AssignRole) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRole", ctx, command)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockRoleAssigningMockRecorder) AssignRole(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockRoleAssigning)(nil).AssignRole), ctx, command)
}
