// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/api/files/get/get.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	commands "expire-share/internal/domain/dto/files/commands"
	results "expire-share/internal/domain/dto/files/results"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileGetter is a mock of FileGetter interface.
type MockFileGetter struct {
	ctrl     *gomock.Controller
	recorder *MockFileGetterMockRecorder
}

// MockFileGetterMockRecorder is the mock recorder for MockFileGetter.
type MockFileGetterMockRecorder struct {
	mock *MockFileGetter
}

// NewMockFileGetter creates a new mock instance.
func NewMockFileGetter(ctrl *gomock.Controller) *MockFileGetter {
	mock := &MockFileGetter{ctrl: ctrl}
	mock.recorder = &MockFileGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileGetter) EXPECT() *MockFileGetterMockRecorder {
	return m.recorder
}

// GetFileByAlias mocks base method.
func (m *MockFileGetter) GetFileByAlias(ctx context.Context, command commands.GetFile) (*results.GetFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileByAlias", ctx, command)
	ret0, _ := ret[0].(*results.GetFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileByAlias indicates an expected call of GetFileByAlias.
func (mr *MockFileGetterMockRecorder) GetFileByAlias(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileByAlias", reflect.TypeOf((*MockFileGetter)(nil).GetFileByAlias), ctx, command)
}
