// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/api/auth/refresh/refresh.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	commands "expire-share/internal/domain/dto/auth/commands"
	results "expire-share/internal/domain/dto/auth/results"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockTokenRefresh is a mock of TokenRefresh interface.
type MockTokenRefresh struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRefreshMockRecorder
}

// MockTokenRefreshMockRecorder is the mock recorder for MockTokenRefresh.
type MockTokenRefreshMockRecorder struct {
	mock *MockTokenRefresh
}

// NewMockTokenRefresh creates a new mock instance.
func NewMockTokenRefresh(ctrl *gomock.Controller) *MockTokenRefresh {
	mock := &MockTokenRefresh{ctrl: ctrl}
	mock.recorder = &MockTokenRefreshMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRefresh) EXPECT() *MockTokenRefreshMockRecorder {
	return m.recorder
}

// Refresh mocks base method.
func (m *MockTokenRefresh) Refresh(ctx context.Context, command commands.Refresh) (*results.Refresh, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", ctx, command)
	ret0, _ := ret[0].(*results.Refresh)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refresh indicates an expected call of Refresh.
func (mr *MockTokenRefreshMockRecorder) Refresh(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockTokenRefresh)(nil).Refresh), ctx, command)
}
