// Code generated by MockGen. DO NOT EDIT.
// Source: internal/delivery/handlers/api/upload/upload.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	commands "expire-share/internal/domain/dto/files/commands"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileUploader is a mock of FileUploader interface.
type MockFileUploader struct {
	ctrl     *gomock.Controller
	recorder *MockFileUploaderMockRecorder
}

// MockFileUploaderMockRecorder is the mock recorder for MockFileUploader.
type MockFileUploaderMockRecorder struct {
	mock *MockFileUploader
}

// NewMockFileUploader creates a new mock instance.
func NewMockFileUploader(ctrl *gomock.Controller) *MockFileUploader {
	mock := &MockFileUploader{ctrl: ctrl}
	mock.recorder = &MockFileUploaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileUploader) EXPECT() *MockFileUploaderMockRecorder {
	return m.recorder
}

// UploadFile mocks base method.
func (m *MockFileUploader) UploadFile(ctx context.Context, command commands.UploadFile) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadFile", ctx, command)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadFile indicates an expected call of UploadFile.
func (mr *MockFileUploaderMockRecorder) UploadFile(ctx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadFile", reflect.TypeOf((*MockFileUploader)(nil).UploadFile), ctx, command)
}
