// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/storage/files.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	results "expire-share/internal/domain/dto/files/results"
	io "io"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFile is a mock of File interface.
type MockFile struct {
	ctrl     *gomock.Controller
	recorder *MockFileMockRecorder
}

// MockFileMockRecorder is the mock recorder for MockFile.
type MockFileMockRecorder struct {
	mock *MockFile
}

// NewMockFile creates a new mock instance.
func NewMockFile(ctrl *gomock.Controller) *MockFile {
	mock := &MockFile{ctrl: ctrl}
	mock.recorder = &MockFileMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFile) EXPECT() *MockFileMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockFile) Delete(ctx context.Context, alias string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, alias)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockFileMockRecorder) Delete(ctx, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockFile)(nil).Delete), ctx, alias)
}

// Download mocks base method.
func (m *MockFile) Download(ctx context.Context, alias string) (*results.DownloadFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Download", ctx, alias)
	ret0, _ := ret[0].(*results.DownloadFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Download indicates an expected call of Download.
func (mr *MockFileMockRecorder) Download(ctx, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Download", reflect.TypeOf((*MockFile)(nil).Download), ctx, alias)
}

// Upload mocks base method.
func (m *MockFile) Upload(ctx context.Context, file io.Reader, alias, filename string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, file, alias, filename)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockFileMockRecorder) Upload(ctx, file, alias, filename interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockFile)(nil).Upload), ctx, file, alias, filename)
}
