// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/interfaces/repositories/files_repo.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	commands "expire-share/internal/domain/dto/files/commands"
	entities "expire-share/internal/domain/entities"
	tx "expire-share/internal/domain/interfaces/tx"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockFileRepo is a mock of FileRepo interface.
type MockFileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepoMockRecorder
}

// MockFileRepoMockRecorder is the mock recorder for MockFileRepo.
type MockFileRepoMockRecorder struct {
	mock *MockFileRepo
}

// NewMockFileRepo creates a new mock instance.
func NewMockFileRepo(ctrl *gomock.Controller) *MockFileRepo {
	mock := &MockFileRepo{ctrl: ctrl}
	mock.recorder = &MockFileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepo) EXPECT() *MockFileRepoMockRecorder {
	return m.recorder
}

// AddFileTx mocks base method.
func (m *MockFileRepo) AddFileTx(ctx context.Context, tx tx.Tx, command commands.AddFile) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddFileTx", ctx, tx, command)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddFileTx indicates an expected call of AddFileTx.
func (mr *MockFileRepoMockRecorder) AddFileTx(ctx, tx, command interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFileTx", reflect.TypeOf((*MockFileRepo)(nil).AddFileTx), ctx, tx, command)
}

// BeginTx mocks base method.
func (m *MockFileRepo) BeginTx(ctx context.Context) (tx.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(tx.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockFileRepoMockRecorder) BeginTx(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockFileRepo)(nil).BeginTx), ctx)
}

// DecrementDownloadsByAliasTx mocks base method.
func (m *MockFileRepo) DecrementDownloadsByAliasTx(ctx context.Context, tx tx.Tx, alias string) (int16, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementDownloadsByAliasTx", ctx, tx, alias)
	ret0, _ := ret[0].(int16)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecrementDownloadsByAliasTx indicates an expected call of DecrementDownloadsByAliasTx.
func (mr *MockFileRepoMockRecorder) DecrementDownloadsByAliasTx(ctx, tx, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementDownloadsByAliasTx", reflect.TypeOf((*MockFileRepo)(nil).DecrementDownloadsByAliasTx), ctx, tx, alias)
}

// DeleteExpiredFilesTx mocks base method.
func (m *MockFileRepo) DeleteExpiredFilesTx(ctx context.Context, tx tx.Tx, limit int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteExpiredFilesTx", ctx, tx, limit)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteExpiredFilesTx indicates an expected call of DeleteExpiredFilesTx.
func (mr *MockFileRepoMockRecorder) DeleteExpiredFilesTx(ctx, tx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteExpiredFilesTx", reflect.TypeOf((*MockFileRepo)(nil).DeleteExpiredFilesTx), ctx, tx, limit)
}

// DeleteFileTx mocks base method.
func (m *MockFileRepo) DeleteFileTx(ctx context.Context, tx tx.Tx, alias string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteFileTx", ctx, tx, alias)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteFileTx indicates an expected call of DeleteFileTx.
func (mr *MockFileRepoMockRecorder) DeleteFileTx(ctx, tx, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteFileTx", reflect.TypeOf((*MockFileRepo)(nil).DeleteFileTx), ctx, tx, alias)
}

// GetFileByAlias mocks base method.
func (m *MockFileRepo) GetFileByAlias(ctx context.Context, alias string) (*entities.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFileByAlias", ctx, alias)
	ret0, _ := ret[0].(*entities.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFileByAlias indicates an expected call of GetFileByAlias.
func (mr *MockFileRepoMockRecorder) GetFileByAlias(ctx, alias interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFileByAlias", reflect.TypeOf((*MockFileRepo)(nil).GetFileByAlias), ctx, alias)
}

// GetFilesByUserID mocks base method.
func (m *MockFileRepo) GetFilesByUserID(ctx context.Context, userID int64) ([]entities.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesByUserID", ctx, userID)
	ret0, _ := ret[0].([]entities.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilesByUserID indicates an expected call of GetFilesByUserID.
func (mr *MockFileRepoMockRecorder) GetFilesByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesByUserID", reflect.TypeOf((*MockFileRepo)(nil).GetFilesByUserID), ctx, userID)
}

// GetFilesStatByUserID mocks base method.
func (m *MockFileRepo) GetFilesStatByUserID(ctx context.Context, userID int64) (*entities.FilesStat, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilesStatByUserID", ctx, userID)
	ret0, _ := ret[0].(*entities.FilesStat)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilesStatByUserID indicates an expected call of GetFilesStatByUserID.
func (mr *MockFileRepoMockRecorder) GetFilesStatByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilesStatByUserID", reflect.TypeOf((*MockFileRepo)(nil).GetFilesStatByUserID), ctx, userID)
}
