version: "3"

vars:
  COMPOSE_CMD: docker compose
  SERVICE_NAME: expire-share

tasks:
  default:
    desc: "Commands list"
    cmds:
      - task --list --color
  mocks:
    desc: "Generating all mocks from domain interfaces"
    cmds:
      - chmod +x ./scripts/gen_mocks.sh
      - ./scripts/gen_mocks.sh
  test:
    desc: "Run all tests"
    cmds:
      - go test -v -coverprofile=coverage.out ./internal/delivery/... ./internal/services/... ./internal/lib/...
  test:cover:
    desc: "Run all test and open coverage report"
    cmds:
      - task test
      - go tool cover -html=coverage.out -o coverage.html
  migrate:up:
    desc: "Up db migrations"
    cmds:
      - go run ./cmd/migrate/main.go up
  migrate:down:
    desc: "Down a db migration"
    cmds:
      - go run ./cmd/migrate/main.go down
  docs:swagger:
    desc: "Generate swagger documentation"
    cmds:
      - swag fmt
      - "swag init -g cmd/{{.SERVICE_NAME}}/main.go -o ./docs"
  docker:up:
    desc: "Up docker container"
    cmds:
      - "{{.COMPOSE_CMD}} up -d --build"
  docker:down:
    desc: "Down docker container"
    cmds:
      - "{{.COMPOSE_CMD}} down"
  docker:logs:
    desc: "Show docker container logs"
    cmds:
      - "{{.COMPOSE_CMD}} logs -f {{.SERVICE_NAME}}"
  docker:restart:
    desc: "Restart {{.SERVICE_NAME}}"
    cmds:
      - "{{.COMPOSE_CMD}} restart {{.SERVICE_NAME}}"