env: "dev" # prod, local, dev
db_host: "mysql:3306"
storage:
  type: "local"
  path: "./storage/"
  max_file_size: "500mb"
http_server:
  port: 8080
  timeout: 4s
  idle_timeout: 60s
  cors:
    allowed_credentials: true
    max_age: 86400 # 24h
redis:
  addr: "redis:6379"
  db: 0
  dial_timeout: 10s
  timeout: 5s
  max_retries: 1
rate_limiter:
  admin:
    max_attempts: 3
    window: 20m
    block_duration: 30m
  register:
    max_attempts: 5
    window: 1h
    block_duration: 24h
  files:
    max_attempts: 10
    window: 20m
    block_duration: 10m
service:
  default_ttl: 1h
  default_max_downloads: 1
  alias_length: 6
  file_worker_delay: 5m
  permissions:
    max_uploaded_files_for_vip: 10
    max_uploaded_files_for_user: 1
auth_service:
  addr: "auth-service:5505"
