env: "local" # prod, local, dev
db_host: "127.0.0.1:3306"
storage:
  type: "local"
  path: "./storage/"
  max_file_size: "500mb"
http_server:
  port: 6010
  timeout: 4s
  idle_timeout: 60s
  cors:
    allowed_credentials: true
    max_age: 300 # 5m
redis:
  addr: "127.0.0.1:6379"
  db: 0
  dial_timeout: 10s
  timeout: 5s
  max_retries: 1
rate_limiter:
  admin:
    field: "admin"
    max_attempts: 3
    window: 20m
    block_duration: 30m
  register:
    field: "register"
    max_attempts: 5
    window: 1h
    block_duration: 12h
  files:
    field: "files"
    max_attempts: 10
    window: 20m
    block_duration: 10m
service:
  default_ttl: 1h
  default_max_downloads: 1
  alias_length: 6
  file_worker_delay: 1m
  permissions:
    max_uploaded_files_for_vip: 10
    max_uploaded_files_for_user: 1
auth_service:
  addr: "localhost:5505"
